apiVersion: v1
kind: Pod
metadata:
  name: cm-env-demo
  labels:
    app: db-client
    team: dev
spec:
  containers:
  - name: cm-env-demo
    image: nginx
    imagePullPolicy: Always
    env:
    - name: ANOTHER_PARAM
      valueFrom:
        configMapKeyRef:
          name: my-app-config
          key: another-param
    - name: EXTRA_PARAM
      valueFrom:
        configMapKeyRef:
          name: my-app-config
          key: extra-param
    volumeMounts:
    - name: config-volume
      mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: my-app-config
  restartPolicy: Never
