apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    app: db-client
spec:
  containers:
  - name: envar-demo-container
    image: nginx
    env:
    - name: DB_PASS
      value: MyPassw0rD
    - name: DB_SERVER
      value: mysql01
    - name: DEMO_GREETING
      value: "Hello from the environment"
