apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
  labels:
    app: db-client
spec:
  containers:
  - name: cm-env-demo
    image: nginx
    imagePullPolicy: Always
    env:
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_PASS
    - name: DB_SERVER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_SERVER
    volumeMounts:
    - name: tls-certs
      mountPath: /tls
  volumes:
    - name: tls-certs
      secret:
        secretName: app-tls
  restartPolicy: Never
